# -*- coding: utf-8 -*-
"""
ÒÖÖÆ²ßÂÔÅäÖÃÍÆËÍAPI - »ùÓÚSSHÎÄ¼þÍÆËÍ

¹¦ÄÜËµÃ÷:
1. IPºÚÃûµ¥ÍÆËÍ: ½«Æ½Ì¨Êý¾Ý¿âÖÐµÄIPµØÖ·ÁÐ±íÍÆËÍµ½Íø¹ØÉè±¸£¬Ð´Èëip_blacklist.txtÎÄ¼þ
2. ÓòÃûºÚÃûµ¥ÍÆËÍ: ½«Æ½Ì¨Êý¾Ý¿âÖÐµÄÓòÃûÁÐ±íÍÆËÍµ½DNS·þÎñÆ÷£¬Ð´Èëdomain_blacklist.txtÎÄ¼þ
3. ¶ª°ü²ßÂÔÍÆËÍ: ½«Æ½Ì¨Êý¾Ý¿âÖÐµÄ¶ª°ü²ßÂÔ£¨IP+¶ª°üÂÊ£©ÍÆËÍµ½Íø¹ØÉè±¸£¬Ð´Èëpacket_loss.jsonÎÄ¼þ

ÅäÖÃÒªÇó:
- config.pyÖÐÅäÖÃIP_BLACKLIST_CONFIG¡¢DOMAIN_BLACKLIST_CONFIG¡¢PACKET_LOSS_CONFIG
- Ã¿¸ö²ßÂÔ¿ÉÒÔÅäÖÃ²»Í¬µÄÔ¶³Ì·þÎñÆ÷SSHÁ¬½ÓÐÅÏ¢
"""
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Dict
import json
import logging
import paramiko
from config import IP_BLACKLIST_CONFIG, DOMAIN_BLACKLIST_CONFIG, PACKET_LOSS_CONFIG
from router.suppression import get_db_connection

router = APIRouter()
logger = logging.getLogger(__name__)


class ConfigPushManager:
    """ÅäÖÃÍÆËÍ¹ÜÀíÆ÷ - Í¨¹ýSSHÍÆËÍÅäÖÃµ½Ô¶³ÌÉè±¸"""
    
    def __init__(self, host: str, port: int, username: str, password: str, config_path: str):
        self.host = host
        self.port = port
        self.username = username
        self.password = password
        self.config_path = config_path  # Ô¶³ÌÉè±¸µÄÅäÖÃÄ¿Â¼£¬Èç /opt/suppression_config
        
    def _get_sftp_client(self):
        """»ñÈ¡SFTP¿Í»§¶Ë"""
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(
            self.host,
            port=self.port,
            username=self.username,
            password=self.password,
            timeout=10
        )
        return ssh.open_sftp(), ssh
        
    def push_ip_blacklist(self, ip_list: List[str]) -> bool:
        """ÍÆËÍIPºÚÃûµ¥ÅäÖÃÎÄ¼þ"""
        try:
            sftp, ssh = self._get_sftp_client()
            
            # Éú³ÉÅäÖÃÎÄ¼þÄÚÈÝ
            content = "# IP Blacklist - Auto-generated by platform\n"
            content += f"# Total IPs: {len(ip_list)}\n"
            for ip in ip_list:
                content += f"{ip}\n"
                
            # Ð´ÈëÔ¶³ÌÎÄ¼þ
            remote_file = f"{self.config_path}/ip_blacklist.txt"
            with sftp.open(remote_file, 'w') as f:
                f.write(content)
                
            sftp.close()
            ssh.close()
            
            logger.info(f"IPºÚÃûµ¥ÒÑÍÆËÍµ½ {self.host}:{remote_file}, ¹²{len(ip_list)}Ìõ")
            return True
            
        except Exception as e:
            logger.error(f"ÍÆËÍIPºÚÃûµ¥Ê§°Ü: {e}")
            return False
            
    def push_domain_blacklist(self, domain_list: List[str]) -> bool:
        """ÍÆËÍÓòÃûºÚÃûµ¥ÅäÖÃÎÄ¼þ"""
        try:
            sftp, ssh = self._get_sftp_client()
            
            # Éú³ÉÅäÖÃÎÄ¼þÄÚÈÝ
            content = "# Domain Blacklist - Auto-generated by platform\n"
            content += f"# Total Domains: {len(domain_list)}\n"
            for domain in domain_list:
                content += f"{domain}\n"
                
            # Ð´ÈëÔ¶³ÌÎÄ¼þ
            remote_file = f"{self.config_path}/domain_blacklist.txt"
            with sftp.open(remote_file, 'w') as f:
                f.write(content)
                
            sftp.close()
            ssh.close()
            
            logger.info(f"ÓòÃûºÚÃûµ¥ÒÑÍÆËÍµ½ {self.host}:{remote_file}, ¹²{len(domain_list)}Ìõ")
            return True
            
        except Exception as e:
            logger.error(f"ÍÆËÍÓòÃûºÚÃûµ¥Ê§°Ü: {e}")
            return False
            
    def push_packet_loss_policy(self, policy_dict: Dict[str, float]) -> bool:
        """ÍÆËÍ¶ª°ü²ßÂÔÅäÖÃÎÄ¼þ£¨JSON¸ñÊ½£©"""
        try:
            sftp, ssh = self._get_sftp_client()
            
            # Éú³ÉJSONÅäÖÃ
            content = json.dumps(policy_dict, indent=2, ensure_ascii=False)
            
            # Ð´ÈëÔ¶³ÌÎÄ¼þ
            remote_file = f"{self.config_path}/packet_loss.json"
            with sftp.open(remote_file, 'w') as f:
                f.write(content)
                
            sftp.close()
            ssh.close()
            
            logger.info(f"¶ª°ü²ßÂÔÒÑÍÆËÍµ½ {self.host}:{remote_file}, ¹²{len(policy_dict)}Ìõ")
            return True
            
        except Exception as e:
            logger.error(f"ÍÆËÍ¶ª°ü²ßÂÔÊ§°Ü: {e}")
            return False


# È«¾ÖÅäÖÃÍÆËÍ¹ÜÀíÆ÷£¨·Ö±ð¹ÜÀí²»Í¬µÄÔ¶³ÌÉè±¸£©
ip_blacklist_manager = None
domain_blacklist_manager = None
packet_loss_manager = None


def init_config_push_manager():
    """³õÊ¼»¯ÅäÖÃÍÆËÍ¹ÜÀíÆ÷"""
    global ip_blacklist_manager, domain_blacklist_manager, packet_loss_manager
    
    # 1. ³õÊ¼»¯IPºÚÃûµ¥¹ÜÀíÆ÷
    if IP_BLACKLIST_CONFIG.get('enabled', False):
        try:
            ip_blacklist_manager = ConfigPushManager(
                host=IP_BLACKLIST_CONFIG['host'],
                port=IP_BLACKLIST_CONFIG['port'],
                username=IP_BLACKLIST_CONFIG['username'],
                password=IP_BLACKLIST_CONFIG['password'],
                config_path=IP_BLACKLIST_CONFIG['config_path']
            )
            logger.info(f"? IPºÚÃûµ¥ÍÆËÍ¹ÜÀíÆ÷ÒÑ³õÊ¼»¯ -> {IP_BLACKLIST_CONFIG['host']}")
        except Exception as e:
            logger.error(f"? IPºÚÃûµ¥ÍÆËÍ¹ÜÀíÆ÷³õÊ¼»¯Ê§°Ü: {e}")
    else:
        logger.warning("??  IPºÚÃûµ¥ÍÆËÍ¹¦ÄÜÎ´ÆôÓÃ")
    
    # 2. ³õÊ¼»¯ÓòÃûºÚÃûµ¥¹ÜÀíÆ÷
    if DOMAIN_BLACKLIST_CONFIG.get('enabled', False):
        try:
            domain_blacklist_manager = ConfigPushManager(
                host=DOMAIN_BLACKLIST_CONFIG['host'],
                port=DOMAIN_BLACKLIST_CONFIG['port'],
                username=DOMAIN_BLACKLIST_CONFIG['username'],
                password=DOMAIN_BLACKLIST_CONFIG['password'],
                config_path=DOMAIN_BLACKLIST_CONFIG['config_path']
            )
            logger.info(f"? ÓòÃûºÚÃûµ¥ÍÆËÍ¹ÜÀíÆ÷ÒÑ³õÊ¼»¯ -> {DOMAIN_BLACKLIST_CONFIG['host']}")
        except Exception as e:
            logger.error(f"? ÓòÃûºÚÃûµ¥ÍÆËÍ¹ÜÀíÆ÷³õÊ¼»¯Ê§°Ü: {e}")
    else:
        logger.warning("??  ÓòÃûºÚÃûµ¥ÍÆËÍ¹¦ÄÜÎ´ÆôÓÃ")
    
    # 3. ³õÊ¼»¯¶ª°ü²ßÂÔ¹ÜÀíÆ÷
    if PACKET_LOSS_CONFIG.get('enabled', False):
        try:
            packet_loss_manager = ConfigPushManager(
                host=PACKET_LOSS_CONFIG['host'],
                port=PACKET_LOSS_CONFIG['port'],
                username=PACKET_LOSS_CONFIG['username'],
                password=PACKET_LOSS_CONFIG['password'],
                config_path=PACKET_LOSS_CONFIG['config_path']
            )
            logger.info(f"? ¶ª°ü²ßÂÔÍÆËÍ¹ÜÀíÆ÷ÒÑ³õÊ¼»¯ -> {PACKET_LOSS_CONFIG['host']}")
        except Exception as e:
            logger.error(f"? ¶ª°ü²ßÂÔÍÆËÍ¹ÜÀíÆ÷³õÊ¼»¯Ê§°Ü: {e}")
    else:
        logger.warning("??  ¶ª°ü²ßÂÔÍÆËÍ¹¦ÄÜÎ´ÆôÓÃ")


# ==================== API½Ó¿Ú ====================

@router.post("/config-push/ip-blacklist")
async def push_ip_blacklist():
    """
    ÍÆËÍIPºÚÃûµ¥µ½Íø¹ØÉè±¸
    
    ÍÆËÍÄÚÈÝ:
    - ´ÓÊý¾Ý¿â±í ip_blacklist ¶ÁÈ¡ËùÓÐIPµØÖ·
    - Éú³É´¿ÎÄ±¾¸ñÊ½ÎÄ¼þ ip_blacklist.txt
    - Í¨¹ýSSHÍÆËÍµ½Íø¹ØÉè±¸µÄ /opt/suppression_config/ Ä¿Â¼
    - ¸ñÊ½Ê¾Àý:
      192.168.1.100
      10.0.0.50
      172.16.0.10
    
    Ä¿±êÉè±¸: IP_BLACKLIST_CONFIGÖÐÅäÖÃµÄÍø¹ØÉè±¸
    """
    if ip_blacklist_manager is None:
        raise HTTPException(status_code=503, detail="IPºÚÃûµ¥ÍÆËÍ·þÎñÎ´³õÊ¼»¯£¬Çë¼ì²éconfig.pyÖÐµÄIP_BLACKLIST_CONFIG")
        
    conn = get_db_connection()
    try:
        cursor = conn.cursor()
        cursor.execute("SELECT ip_address FROM ip_blacklist ORDER BY created_at DESC")
        items = cursor.fetchall()
        
        ip_list = [item['ip_address'] for item in items]
        
        success = ip_blacklist_manager.push_ip_blacklist(ip_list)
        
        if success:
            return {
                "status": "success",
                "message": f"IPºÚÃûµ¥ÒÑÍÆËÍµ½Íø¹ØÉè±¸ {IP_BLACKLIST_CONFIG['host']}£¬¹²{len(ip_list)}Ìõ",
                "count": len(ip_list),
                "target": f"{IP_BLACKLIST_CONFIG['host']}:{IP_BLACKLIST_CONFIG['config_path']}/ip_blacklist.txt"
            }
        else:
            raise HTTPException(status_code=500, detail="ÍÆËÍÊ§°Ü")
            
    except Exception as e:
        logger.error(f"ÍÆËÍIPºÚÃûµ¥Ê§°Ü: {e}")
        raise HTTPException(status_code=500, detail=f"ÍÆËÍÊ§°Ü: {str(e)}")
    finally:
        conn.close()


@router.post("/config-push/domain-blacklist")
async def push_domain_blacklist():
    """
    ÍÆËÍÓòÃûºÚÃûµ¥µ½DNS·þÎñÆ÷
    
    ÍÆËÍÄÚÈÝ:
    - ´ÓÊý¾Ý¿â±í domain_blacklist ¶ÁÈ¡ËùÓÐÓòÃû
    - Éú³É´¿ÎÄ±¾¸ñÊ½ÎÄ¼þ domain_blacklist.txt
    - Í¨¹ýSSHÍÆËÍµ½DNS·þÎñÆ÷µÄ /opt/suppression_config/ Ä¿Â¼
    - ¸ñÊ½Ê¾Àý:
      malware.com
      botnet.net
      c2server.org
    
    Ä¿±êÉè±¸: DOMAIN_BLACKLIST_CONFIGÖÐÅäÖÃµÄDNS·þÎñÆ÷
    """
    if domain_blacklist_manager is None:
        raise HTTPException(status_code=503, detail="ÓòÃûºÚÃûµ¥ÍÆËÍ·þÎñÎ´³õÊ¼»¯£¬Çë¼ì²éconfig.pyÖÐµÄDOMAIN_BLACKLIST_CONFIG")
        
    conn = get_db_connection()
    try:
        cursor = conn.cursor()
        cursor.execute("SELECT domain FROM domain_blacklist ORDER BY created_at DESC")
        items = cursor.fetchall()
        
        domain_list = [item['domain'] for item in items]
        
        success = domain_blacklist_manager.push_domain_blacklist(domain_list)
        
        if success:
            return {
                "status": "success",
                "message": f"ÓòÃûºÚÃûµ¥ÒÑÍÆËÍµ½DNS·þÎñÆ÷ {DOMAIN_BLACKLIST_CONFIG['host']}£¬¹²{len(domain_list)}Ìõ",
                "count": len(domain_list),
                "target": f"{DOMAIN_BLACKLIST_CONFIG['host']}:{DOMAIN_BLACKLIST_CONFIG['config_path']}/domain_blacklist.txt"
            }
        else:
            raise HTTPException(status_code=500, detail="ÍÆËÍÊ§°Ü")
            
    except Exception as e:
        logger.error(f"ÍÆËÍÓòÃûºÚÃûµ¥Ê§°Ü: {e}")
        raise HTTPException(status_code=500, detail=f"ÍÆËÍÊ§°Ü: {str(e)}")
    finally:
        conn.close()


@router.post("/config-push/packet-loss")
async def push_packet_loss_policy():
    """
    ÍÆËÍ¶ª°ü²ßÂÔµ½Íø¹ØÉè±¸
    
    ÍÆËÍÄÚÈÝ:
    - ´ÓÊý¾Ý¿â±í packet_loss_policy ¶ÁÈ¡ËùÓÐÆôÓÃµÄ¶ª°ü²ßÂÔ(IPµØÖ·+¶ª°üÂÊ)
    - Éú³ÉJSON¸ñÊ½ÎÄ¼þ packet_loss.json
    - Í¨¹ýSSHÍÆËÍµ½Íø¹ØÉè±¸µÄ /opt/suppression_config/ Ä¿Â¼
    - ¸ñÊ½Ê¾Àý:
      {
        "192.168.1.100": 0.3,  // 30%¶ª°üÂÊ
        "10.0.0.50": 0.5,      // 50%¶ª°üÂÊ
        "172.16.0.10": 0.2     // 20%¶ª°üÂÊ
      }
    
    Ä¿±êÉè±¸: PACKET_LOSS_CONFIGÖÐÅäÖÃµÄÍø¹ØÉè±¸
    """
    if packet_loss_manager is None:
        raise HTTPException(status_code=503, detail="¶ª°ü²ßÂÔÍÆËÍ·þÎñÎ´³õÊ¼»¯£¬Çë¼ì²éconfig.pyÖÐµÄPACKET_LOSS_CONFIG")
        
    conn = get_db_connection()
    try:
        cursor = conn.cursor()
        cursor.execute("""
            SELECT ip_address, loss_rate
            FROM packet_loss_policy
            WHERE enabled = TRUE
            ORDER BY created_at DESC
        """)
        items = cursor.fetchall()
        
        # ×ª»»Îª×Öµä {ip: loss_rate}
        policy_dict = {item['ip_address']: item['loss_rate'] for item in items}
        
        success = packet_loss_manager.push_packet_loss_policy(policy_dict)
        
        if success:
            return {
                "status": "success",
                "message": f"¶ª°ü²ßÂÔÒÑÍÆËÍµ½Íø¹ØÉè±¸ {PACKET_LOSS_CONFIG['host']}£¬¹²{len(policy_dict)}Ìõ",
                "count": len(policy_dict),
                "target": f"{PACKET_LOSS_CONFIG['host']}:{PACKET_LOSS_CONFIG['config_path']}/packet_loss.json"
            }
        else:
            raise HTTPException(status_code=500, detail="ÍÆËÍÊ§°Ü")
            
    except Exception as e:
        logger.error(f"ÍÆËÍ¶ª°ü²ßÂÔÊ§°Ü: {e}")
        raise HTTPException(status_code=500, detail=f"ÍÆËÍÊ§°Ü: {str(e)}")
    finally:
        conn.close()


@router.post("/config-push/all")
async def push_all_config():
    """
    Ò»¼üÍÆËÍËùÓÐÒÖÖÆ²ßÂÔÅäÖÃµ½¸÷×ÔµÄÔ¶³ÌÉè±¸
    °üÀ¨£ºIPºÚÃûµ¥(Íø¹Ø) + ÓòÃûºÚÃûµ¥(DNS) + ¶ª°ü²ßÂÔ(Íø¹Ø)
    """
    results = {}
    conn = get_db_connection()
    
    try:
        cursor = conn.cursor()
        
        # 1. ÍÆËÍIPºÚÃûµ¥µ½Íø¹ØÉè±¸
        if ip_blacklist_manager:
            cursor.execute("SELECT ip_address FROM ip_blacklist")
            ip_items = cursor.fetchall()
            ip_list = [item['ip_address'] for item in ip_items]
            results['ip_blacklist'] = {
                "success": ip_blacklist_manager.push_ip_blacklist(ip_list),
                "count": len(ip_list),
                "target": IP_BLACKLIST_CONFIG['host']
            }
        else:
            results['ip_blacklist'] = {
                "success": False,
                "count": 0,
                "message": "·þÎñÎ´ÆôÓÃ"
            }
        
        # 2. ÍÆËÍÓòÃûºÚÃûµ¥µ½DNS·þÎñÆ÷
        if domain_blacklist_manager:
            cursor.execute("SELECT domain FROM domain_blacklist")
            domain_items = cursor.fetchall()
            domain_list = [item['domain'] for item in domain_items]
            results['domain_blacklist'] = {
                "success": domain_blacklist_manager.push_domain_blacklist(domain_list),
                "count": len(domain_list),
                "target": DOMAIN_BLACKLIST_CONFIG['host']
            }
        else:
            results['domain_blacklist'] = {
                "success": False,
                "count": 0,
                "message": "·þÎñÎ´ÆôÓÃ"
            }
        
        # 3. ÍÆËÍ¶ª°ü²ßÂÔµ½Íø¹ØÉè±¸
        if packet_loss_manager:
            cursor.execute("SELECT ip_address, loss_rate FROM packet_loss_policy WHERE enabled = TRUE")
            policy_items = cursor.fetchall()
            policy_dict = {item['ip_address']: item['loss_rate'] for item in policy_items}
            results['packet_loss'] = {
                "success": packet_loss_manager.push_packet_loss_policy(policy_dict),
                "count": len(policy_dict),
                "target": PACKET_LOSS_CONFIG['host']
            }
        else:
            results['packet_loss'] = {
                "success": False,
                "count": 0,
                "message": "·þÎñÎ´ÆôÓÃ"
            }
        
        # ¼ì²éÊÇ·ñÈ«²¿³É¹¦
        all_success = all(r.get('success', False) for r in results.values())
        
        return {
            "status": "success" if all_success else "partial",
            "message": "ÅäÖÃÍÆËÍÍê³É",
            "details": results
        }
        
    except Exception as e:
        logger.error(f"ÍÆËÍÅäÖÃÊ§°Ü: {e}")
        raise HTTPException(status_code=500, detail=f"ÍÆËÍÊ§°Ü: {str(e)}")
    finally:
        conn.close()


@router.get("/config-push/health")
async def check_config_push_health():
    """¼ì²éÅäÖÃÍÆËÍ·þÎñ½¡¿µ×´Ì¬"""
    health_status = {
        "ip_blacklist": {"status": "disabled", "message": "·þÎñÎ´ÆôÓÃ"},
        "domain_blacklist": {"status": "disabled", "message": "·þÎñÎ´ÆôÓÃ"},
        "packet_loss": {"status": "disabled", "message": "·þÎñÎ´ÆôÓÃ"}
    }
    
    # ¼ì²éIPºÚÃûµ¥ÍÆËÍ
    if ip_blacklist_manager:
        try:
            sftp, ssh = ip_blacklist_manager._get_sftp_client()
            sftp.close()
            ssh.close()
            health_status["ip_blacklist"] = {
                "status": "healthy",
                "message": "Á¬½ÓÕý³£",
                "target": f"{IP_BLACKLIST_CONFIG['host']}:{IP_BLACKLIST_CONFIG['config_path']}"
            }
        except Exception as e:
            health_status["ip_blacklist"] = {
                "status": "unhealthy",
                "message": f"Á¬½ÓÊ§°Ü: {str(e)}"
            }
    
    # ¼ì²éÓòÃûºÚÃûµ¥ÍÆËÍ
    if domain_blacklist_manager:
        try:
            sftp, ssh = domain_blacklist_manager._get_sftp_client()
            sftp.close()
            ssh.close()
            health_status["domain_blacklist"] = {
                "status": "healthy",
                "message": "Á¬½ÓÕý³£",
                "target": f"{DOMAIN_BLACKLIST_CONFIG['host']}:{DOMAIN_BLACKLIST_CONFIG['config_path']}"
            }
        except Exception as e:
            health_status["domain_blacklist"] = {
                "status": "unhealthy",
                "message": f"Á¬½ÓÊ§°Ü: {str(e)}"
            }
    
    # ¼ì²é¶ª°ü²ßÂÔÍÆËÍ
    if packet_loss_manager:
        try:
            sftp, ssh = packet_loss_manager._get_sftp_client()
            sftp.close()
            ssh.close()
            health_status["packet_loss"] = {
                "status": "healthy",
                "message": "Á¬½ÓÕý³£",
                "target": f"{PACKET_LOSS_CONFIG['host']}:{PACKET_LOSS_CONFIG['config_path']}"
            }
        except Exception as e:
            health_status["packet_loss"] = {
                "status": "unhealthy",
                "message": f"Á¬½ÓÊ§°Ü: {str(e)}"
            }
    
    # ÅÐ¶ÏÕûÌå×´Ì¬
    all_healthy = all(
        status.get("status") in ["healthy", "disabled"]
        for status in health_status.values()
    )
    
    return {
        "status": "healthy" if all_healthy else "unhealthy",
        "details": health_status
    }


# ==================== 一键部署功能 ====================

@router.post("/config-push/deploy/{service_type}")
async def deploy_config_service(service_type: str):
    """
    一键部署配置服务（IP黑名单/域名黑名单/丢包策略）
    
    service_type: ip-blacklist, domain-blacklist, packet-loss
    
    自动执行：
    1. 创建配置目录
    2. 设置目录权限
    3. 创建初始配置文件
    4. 验证部署
    """
    import time
    from datetime import datetime
    
    # 选择对应的配置
    config_map = {
        "ip-blacklist": IP_BLACKLIST_CONFIG,
        "domain-blacklist": DOMAIN_BLACKLIST_CONFIG,
        "packet-loss": PACKET_LOSS_CONFIG
    }
    
    if service_type not in config_map:
        raise HTTPException(status_code=400, detail=f"不支持的服务类型: {service_type}")
    
    config = config_map[service_type]
    
    if not config.get('enabled', False):
        raise HTTPException(status_code=503, detail=f"{service_type}服务未在config.py中启用")
    
    progress_log = []
    
    def log_progress(step: str, status: str, message: str):
        progress_log.append({
            'step': step,
            'status': status,
            'message': message,
            'timestamp': datetime.now().isoformat()
        })
        logger.info(f"[部署-{service_type}] {step}: {message}")
    
    try:
        # 建立SSH连接
        log_progress("连接SSH", "running", f"正在连接到 {config['host']}:{config['port']}...")
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(
            config['host'],
            port=config['port'],
            username=config['username'],
            password=config['password'],
            timeout=10
        )
        log_progress("连接SSH", "success", "SSH连接成功")
        
        # 步骤1: 创建配置目录
        log_progress("创建目录", "running", f"正在创建配置目录 {config['config_path']}...")
        commands = [
            f"mkdir -p {config['config_path']}",
            f"chown -R {config['username']}:{config['username']} {config['config_path']}",
            f"chmod 755 {config['config_path']}"
        ]
        
        for cmd in commands:
            stdin, stdout, stderr = ssh.exec_command(f"sudo {cmd}")
            exit_status = stdout.channel.recv_exit_status()
            if exit_status != 0:
                error_msg = stderr.read().decode('utf-8')
                log_progress("创建目录", "error", f"命令失败: {cmd}, 错误: {error_msg}")
                raise Exception(f"创建目录失败: {error_msg}")
        
        log_progress("创建目录", "success", f"目录 {config['config_path']} 创建成功")
        
        # 步骤2: 创建初始配置文件
        log_progress("创建配置文件", "running", "正在创建初始配置文件...")
        
        sftp = ssh.open_sftp()
        
        if service_type == "ip-blacklist":
            remote_file = f"{config['config_path']}/ip_blacklist.txt"
            content = "# IP Blacklist - Auto-generated by platform\n# Add one IP per line\n"
            with sftp.open(remote_file, 'w') as f:
                f.write(content)
            log_progress("创建配置文件", "success", f"已创建: {remote_file}")
            
        elif service_type == "domain-blacklist":
            remote_file = f"{config['config_path']}/domain_blacklist.txt"
            content = "# Domain Blacklist - Auto-generated by platform\n# Add one domain per line\n"
            with sftp.open(remote_file, 'w') as f:
                f.write(content)
            log_progress("创建配置文件", "success", f"已创建: {remote_file}")
            
        elif service_type == "packet-loss":
            remote_file = f"{config['config_path']}/packet_loss.json"
            content = json.dumps({}, indent=2)
            with sftp.open(remote_file, 'w') as f:
                f.write(content)
            log_progress("创建配置文件", "success", f"已创建: {remote_file}")
        
        sftp.close()
        
        # 步骤3: 验证部署
        log_progress("验证部署", "running", "正在验证部署...")
        time.sleep(1)
        
        stdin, stdout, stderr = ssh.exec_command(f"ls -la {config['config_path']}")
        dir_output = stdout.read().decode('utf-8')
        
        if config['config_path'].split('/')[-1] in dir_output or remote_file.split('/')[-1] in dir_output:
            log_progress("验证部署", "success", "配置目录和文件验证通过")
        else:
            log_progress("验证部署", "warning", "目录结构可能不完整")
        
        ssh.close()
        
        log_progress("部署完成", "success", f"✅ {service_type}服务部署成功！服务器: {config['host']}")
        
        return {
            'status': 'success',
            'message': f'{service_type}服务部署成功',
            'host': config['host'],
            'config_path': config['config_path'],
            'logs': progress_log
        }
        
    except paramiko.AuthenticationException:
        log_progress("连接SSH", "error", "SSH认证失败，请检查用户名和密码")
        return {
            'status': 'error',
            'message': 'SSH认证失败',
            'logs': progress_log
        }
    except paramiko.SSHException as e:
        log_progress("SSH错误", "error", f"SSH连接错误: {str(e)}")
        return {
            'status': 'error',
            'message': f'SSH错误: {str(e)}',
            'logs': progress_log
        }
    except Exception as e:
        log_progress("未知错误", "error", f"部署失败: {str(e)}")
        logger.exception(f"部署{service_type}服务失败")
        return {
            'status': 'error',
            'message': str(e),
            'logs': progress_log
        }


@router.get("/config-push/status/{service_type}")
async def get_config_service_status(service_type: str):
    """获取配置服务的部署和运行状态"""
    config_map = {
        "ip-blacklist": (IP_BLACKLIST_CONFIG, ip_blacklist_manager),
        "domain-blacklist": (DOMAIN_BLACKLIST_CONFIG, domain_blacklist_manager),
        "packet-loss": (PACKET_LOSS_CONFIG, packet_loss_manager)
    }
    
    if service_type not in config_map:
        raise HTTPException(status_code=400, detail=f"不支持的服务类型: {service_type}")
    
    config, manager = config_map[service_type]
    
    if not config.get('enabled', False):
        return {
            'status': 'error',
            'message': '服务未启用'
        }
    
    if not manager:
        return {
            'status': 'error',
            'message': '管理器未初始化'
        }
    
    try:
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(
            config['host'],
            port=config['port'],
            username=config['username'],
            password=config['password'],
            timeout=5
        )
        
        # 检查目录是否存在
        stdin, stdout, stderr = ssh.exec_command(f"test -d {config['config_path']} && echo 'exists' || echo 'not_exists'")
        dir_exists = stdout.read().decode('utf-8').strip() == 'exists'
        
        # 检查配置文件
        file_map = {
            "ip-blacklist": "ip_blacklist.txt",
            "domain-blacklist": "domain_blacklist.txt",
            "packet-loss": "packet_loss.json"
        }
        config_file = file_map.get(service_type, "")
        
        stdin, stdout, stderr = ssh.exec_command(f"test -f {config['config_path']}/{config_file} && echo 'exists' || echo 'not_exists'")
        file_exists = stdout.read().decode('utf-8').strip() == 'exists'
        
        ssh.close()
        
        return {
            'status': 'success',
            'data': {
                'is_deployed': dir_exists and file_exists,
                'is_configured': config.get('enabled', False),
                'host': config['host'],
                'config_path': config['config_path'],
                'config_file': config_file if file_exists else None
            }
        }
    except Exception as e:
        return {
            'status': 'error',
            'message': str(e)
        }
