# -*- coding: utf-8 -*-
"""
抑制策略配置推送API - 基于SSH文件推送

功能说明:
1. IP黑名单推送: 将平台数据库中的IP地址列表推送到网关设备，写入ip_blacklist.txt文件
2. 域名黑名单推送: 将平台数据库中的域名列表推送到DNS服务器，写入domain_blacklist.txt文件
3. 丢包策略推送: 将平台数据库中的丢包策略（IP+丢包率）推送到网关设备，写入packet_loss.json文件

配置要求:
- config.py中配置IP_BLACKLIST_CONFIG、DOMAIN_BLACKLIST_CONFIG、PACKET_LOSS_CONFIG
- 每个策略可以配置不同的远程服务器SSH连接信息
"""
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Dict
import json
import logging
import paramiko
from config import IP_BLACKLIST_CONFIG, DOMAIN_BLACKLIST_CONFIG, PACKET_LOSS_CONFIG
from router.suppression import get_db_connection

router = APIRouter()
logger = logging.getLogger(__name__)


class ConfigPushManager:
    """配置推送管理器 - 通过SSH推送配置到远程设备"""
    
    def __init__(self, host: str, port: int, username: str, password: str, config_path: str):
        self.host = host
        self.port = port
        self.username = username
        self.password = password
        self.config_path = config_path  # 远程设备的配置目录，如 /opt/suppression_config
        
    def _get_sftp_client(self):
        """获取SFTP客户端"""
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(
            self.host,
            port=self.port,
            username=self.username,
            password=self.password,
            timeout=10
        )
        return ssh.open_sftp(), ssh
        
    def push_ip_blacklist(self, ip_list: List[str]) -> bool:
        """推送IP黑名单配置文件"""
        try:
            sftp, ssh = self._get_sftp_client()
            
            # 生成配置文件内容
            content = "# IP Blacklist - Auto-generated by platform\n"
            content += f"# Total IPs: {len(ip_list)}\n"
            for ip in ip_list:
                content += f"{ip}\n"
                
            # 写入远程文件
            remote_file = f"{self.config_path}/ip_blacklist.txt"
            with sftp.open(remote_file, 'w') as f:
                f.write(content)
                
            sftp.close()
            ssh.close()
            
            logger.info(f"IP黑名单已推送到 {self.host}:{remote_file}, 共{len(ip_list)}条")
            return True
            
        except Exception as e:
            logger.error(f"推送IP黑名单失败: {e}")
            return False
            
    def push_domain_blacklist(self, domain_list: List[str]) -> bool:
        """推送域名黑名单配置文件"""
        try:
            sftp, ssh = self._get_sftp_client()
            
            # 生成配置文件内容
            content = "# Domain Blacklist - Auto-generated by platform\n"
            content += f"# Total Domains: {len(domain_list)}\n"
            for domain in domain_list:
                content += f"{domain}\n"
                
            # 写入远程文件
            remote_file = f"{self.config_path}/domain_blacklist.txt"
            with sftp.open(remote_file, 'w') as f:
                f.write(content)
                
            sftp.close()
            ssh.close()
            
            logger.info(f"域名黑名单已推送到 {self.host}:{remote_file}, 共{len(domain_list)}条")
            return True
            
        except Exception as e:
            logger.error(f"推送域名黑名单失败: {e}")
            return False
            
    def push_packet_loss_policy(self, policy_dict: Dict[str, float]) -> bool:
        """推送丢包策略配置文件（JSON格式）"""
        try:
            sftp, ssh = self._get_sftp_client()
            
            # 生成JSON配置
            content = json.dumps(policy_dict, indent=2, ensure_ascii=False)
            
            # 写入远程文件
            remote_file = f"{self.config_path}/packet_loss.json"
            with sftp.open(remote_file, 'w') as f:
                f.write(content)
                
            sftp.close()
            ssh.close()
            
            logger.info(f"丢包策略已推送到 {self.host}:{remote_file}, 共{len(policy_dict)}条")
            return True
            
        except Exception as e:
            logger.error(f"推送丢包策略失败: {e}")
            return False


# 全局配置推送管理器（分别管理不同的远程设备）
ip_blacklist_manager = None
domain_blacklist_manager = None
packet_loss_manager = None


def init_config_push_manager():
    """初始化配置推送管理器"""
    global ip_blacklist_manager, domain_blacklist_manager, packet_loss_manager
    
    # 1. 初始化IP黑名单管理器
    if IP_BLACKLIST_CONFIG.get('enabled', False):
        try:
            ip_blacklist_manager = ConfigPushManager(
                host=IP_BLACKLIST_CONFIG['host'],
                port=IP_BLACKLIST_CONFIG['port'],
                username=IP_BLACKLIST_CONFIG['username'],
                password=IP_BLACKLIST_CONFIG['password'],
                config_path=IP_BLACKLIST_CONFIG['config_path']
            )
            logger.info(f"✅ IP黑名单推送管理器已初始化 -> {IP_BLACKLIST_CONFIG['host']}")
        except Exception as e:
            logger.error(f"❌ IP黑名单推送管理器初始化失败: {e}")
    else:
        logger.warning("⚠️  IP黑名单推送功能未启用")
    
    # 2. 初始化域名黑名单管理器
    if DOMAIN_BLACKLIST_CONFIG.get('enabled', False):
        try:
            domain_blacklist_manager = ConfigPushManager(
                host=DOMAIN_BLACKLIST_CONFIG['host'],
                port=DOMAIN_BLACKLIST_CONFIG['port'],
                username=DOMAIN_BLACKLIST_CONFIG['username'],
                password=DOMAIN_BLACKLIST_CONFIG['password'],
                config_path=DOMAIN_BLACKLIST_CONFIG['config_path']
            )
            logger.info(f"✅ 域名黑名单推送管理器已初始化 -> {DOMAIN_BLACKLIST_CONFIG['host']}")
        except Exception as e:
            logger.error(f"❌ 域名黑名单推送管理器初始化失败: {e}")
    else:
        logger.warning("⚠️  域名黑名单推送功能未启用")
    
    # 3. 初始化丢包策略管理器
    if PACKET_LOSS_CONFIG.get('enabled', False):
        try:
            packet_loss_manager = ConfigPushManager(
                host=PACKET_LOSS_CONFIG['host'],
                port=PACKET_LOSS_CONFIG['port'],
                username=PACKET_LOSS_CONFIG['username'],
                password=PACKET_LOSS_CONFIG['password'],
                config_path=PACKET_LOSS_CONFIG['config_path']
            )
            logger.info(f"✅ 丢包策略推送管理器已初始化 -> {PACKET_LOSS_CONFIG['host']}")
        except Exception as e:
            logger.error(f"❌ 丢包策略推送管理器初始化失败: {e}")
    else:
        logger.warning("⚠️  丢包策略推送功能未启用")


# ==================== API接口 ==

@router.post("/config-push/ip-blacklist")
async def push_ip_blacklist():
    """
    推送IP黑名单到网关设备
    
    推送内容:
    - 从数据库表 ip_blacklist 读取所有IP地址
    - 生成纯文本格式文件 ip_blacklist.txt
    - 通过SSH推送到网关设备的 /opt/suppression_config/ 目录
    - 格式示例:
      192.168.1.100
      10.0.0.50
      172.16.0.10
    
    目标设备: IP_BLACKLIST_CONFIG中配置的网关设备
    """
    if ip_blacklist_manager is None:
        raise HTTPException(status_code=503, detail="IP黑名单推送服务未初始化，请检查config.py中的IP_BLACKLIST_CONFIG")
        
    conn = get_db_connection()
    try:
        cursor = conn.cursor()
        cursor.execute("SELECT ip_address FROM ip_blacklist ORDER BY created_at DESC")
        items = cursor.fetchall()
        
        ip_list = [item['ip_address'] for item in items]
        
        success = ip_blacklist_manager.push_ip_blacklist(ip_list)
        
        if success:
            return {
                "status": "success",
                "message": f"IP黑名单已推送到网关设备 {IP_BLACKLIST_CONFIG['host']}，共{len(ip_list)}条",
                "count": len(ip_list),
                "target": f"{IP_BLACKLIST_CONFIG['host']}:{IP_BLACKLIST_CONFIG['config_path']}/ip_blacklist.txt"
            }
        else:
            raise HTTPException(status_code=500, detail="推送失败")
            
    except Exception as e:
        logger.error(f"推送IP黑名单失败: {e}")
        raise HTTPException(status_code=500, detail=f"推送失败: {str(e)}")
    finally:
        conn.close()


@router.post("/config-push/domain-blacklist")
async def push_domain_blacklist():
    """
    推送域名黑名单到DNS服务器
    
    推送内容:
    - 从数据库表 domain_blacklist 读取所有域名
    - 生成纯文本格式文件 domain_blacklist.txt
    - 通过SSH推送到DNS服务器的 /opt/suppression_config/ 目录
    - 格式示例:
      malware.com
      botnet.net
      c2server.org
    
    目标设备: DOMAIN_BLACKLIST_CONFIG中配置的DNS服务器
    """
    if domain_blacklist_manager is None:
        raise HTTPException(status_code=503, detail="域名黑名单推送服务未初始化，请检查config.py中的DOMAIN_BLACKLIST_CONFIG")
        
    conn = get_db_connection()
    try:
        cursor = conn.cursor()
        cursor.execute("SELECT domain FROM domain_blacklist ORDER BY created_at DESC")
        items = cursor.fetchall()
        
        domain_list = [item['domain'] for item in items]
        
        success = domain_blacklist_manager.push_domain_blacklist(domain_list)
        
        if success:
            return {
                "status": "success",
                "message": f"域名黑名单已推送到DNS服务器 {DOMAIN_BLACKLIST_CONFIG['host']}，共{len(domain_list)}条",
                "count": len(domain_list),
                "target": f"{DOMAIN_BLACKLIST_CONFIG['host']}:{DOMAIN_BLACKLIST_CONFIG['config_path']}/domain_blacklist.txt"
            }
        else:
            raise HTTPException(status_code=500, detail="推送失败")
            
    except Exception as e:
        logger.error(f"推送域名黑名单失败: {e}")
        raise HTTPException(status_code=500, detail=f"推送失败: {str(e)}")
    finally:
        conn.close()


@router.post("/config-push/packet-loss")
async def push_packet_loss_policy():
    """
    推送丢包策略到网关设备
    
    推送内容:
    - 从数据库表 packet_loss_policy 读取所有启用的丢包策略(IP地址+丢包率)
    - 生成JSON格式文件 packet_loss.json
    - 通过SSH推送到网关设备的 /opt/suppression_config/ 目录
    - 格式示例:
      {
        "192.168.1.100": 0.3,  // 30%丢包率
        "10.0.0.50": 0.5,      // 50%丢包率
        "172.16.0.10": 0.2     // 20%丢包率
      }
    
    目标设备: PACKET_LOSS_CONFIG中配置的网关设备
    """
    if packet_loss_manager is None:
        raise HTTPException(status_code=503, detail="丢包策略推送服务未初始化，请检查config.py中的PACKET_LOSS_CONFIG")
        
    conn = get_db_connection()
    try:
        cursor = conn.cursor()
        cursor.execute("""
            SELECT ip_address, loss_rate
            FROM packet_loss_policy
            WHERE enabled = TRUE
            ORDER BY created_at DESC
        """)
        items = cursor.fetchall()
        
        # 转换为字典 {ip: loss_rate}
        policy_dict = {item['ip_address']: item['loss_rate'] for item in items}
        
        success = packet_loss_manager.push_packet_loss_policy(policy_dict)
        
        if success:
            return {
                "status": "success",
                "message": f"丢包策略已推送到网关设备 {PACKET_LOSS_CONFIG['host']}，共{len(policy_dict)}条",
                "count": len(policy_dict),
                "target": f"{PACKET_LOSS_CONFIG['host']}:{PACKET_LOSS_CONFIG['config_path']}/packet_loss.json"
            }
        else:
            raise HTTPException(status_code=500, detail="推送失败")
            
    except Exception as e:
        logger.error(f"推送丢包策略失败: {e}")
        raise HTTPException(status_code=500, detail=f"推送失败: {str(e)}")
    finally:
        conn.close()


@router.post("/config-push/all")
async def push_all_config():
    """
    一键推送所有抑制策略配置到各自的远程设备
    包括：IP黑名单(网关) + 域名黑名单(DNS) + 丢包策略(网关)
    """
    results = {}
    conn = get_db_connection()
    
    try:
        cursor = conn.cursor()
        
        # 1. 推送IP黑名单到网关设备
        if ip_blacklist_manager:
            cursor.execute("SELECT ip_address FROM ip_blacklist")
            ip_items = cursor.fetchall()
            ip_list = [item['ip_address'] for item in ip_items]
            results['ip_blacklist'] = {
                "success": ip_blacklist_manager.push_ip_blacklist(ip_list),
                "count": len(ip_list),
                "target": IP_BLACKLIST_CONFIG['host']
            }
        else:
            results['ip_blacklist'] = {
                "success": False,
                "count": 0,
                "message": "服务未启用"
            }
        
        # 2. 推送域名黑名单到DNS服务器
        if domain_blacklist_manager:
            cursor.execute("SELECT domain FROM domain_blacklist")
            domain_items = cursor.fetchall()
            domain_list = [item['domain'] for item in domain_items]
            results['domain_blacklist'] = {
                "success": domain_blacklist_manager.push_domain_blacklist(domain_list),
                "count": len(domain_list),
                "target": DOMAIN_BLACKLIST_CONFIG['host']
            }
        else:
            results['domain_blacklist'] = {
                "success": False,
                "count": 0,
                "message": "服务未启用"
            }
        
        # 3. 推送丢包策略到网关设备
        if packet_loss_manager:
            cursor.execute("SELECT ip_address, loss_rate FROM packet_loss_policy WHERE enabled = TRUE")
            policy_items = cursor.fetchall()
            policy_dict = {item['ip_address']: item['loss_rate'] for item in policy_items}
            results['packet_loss'] = {
                "success": packet_loss_manager.push_packet_loss_policy(policy_dict),
                "count": len(policy_dict),
                "target": PACKET_LOSS_CONFIG['host']
            }
        else:
            results['packet_loss'] = {
                "success": False,
                "count": 0,
                "message": "服务未启用"
            }
        
        # 检查是否全部成功
        all_success = all(r.get('success', False) for r in results.values())
        
        return {
            "status": "success" if all_success else "partial",
            "message": "配置推送完成",
            "details": results
        }
        
    except Exception as e:
        logger.error(f"推送配置失败: {e}")
        raise HTTPException(status_code=500, detail=f"推送失败: {str(e)}")
    finally:
        conn.close()


@router.get("/config-push/health")
async def check_config_push_health():
    """检查配置推送服务健康状态"""
    health_status = {
        "ip_blacklist": {"status": "disabled", "message": "服务未启用"},
        "domain_blacklist": {"status": "disabled", "message": "服务未启用"},
        "packet_loss": {"status": "disabled", "message": "服务未启用"}
    }
    
    # 检查IP黑名单推送
    if ip_blacklist_manager:
        try:
            sftp, ssh = ip_blacklist_manager._get_sftp_client()
            sftp.close()
            ssh.close()
            health_status["ip_blacklist"] = {
                "status": "healthy",
                "message": "连接正常",
                "target": f"{IP_BLACKLIST_CONFIG['host']}:{IP_BLACKLIST_CONFIG['config_path']}"
            }
        except Exception as e:
            health_status["ip_blacklist"] = {
                "status": "unhealthy",
                "message": f"连接失败: {str(e)}"
            }
    
    # 检查域名黑名单推送
    if domain_blacklist_manager:
        try:
            sftp, ssh = domain_blacklist_manager._get_sftp_client()
            sftp.close()
            ssh.close()
            health_status["domain_blacklist"] = {
                "status": "healthy",
                "message": "连接正常",
                "target": f"{DOMAIN_BLACKLIST_CONFIG['host']}:{DOMAIN_BLACKLIST_CONFIG['config_path']}"
            }
        except Exception as e:
            health_status["domain_blacklist"] = {
                "status": "unhealthy",
                "message": f"连接失败: {str(e)}"
            }
    
    # 检查丢包策略推送
    if packet_loss_manager:
        try:
            sftp, ssh = packet_loss_manager._get_sftp_client()
            sftp.close()
            ssh.close()
            health_status["packet_loss"] = {
                "status": "healthy",
                "message": "连接正常",
                "target": f"{PACKET_LOSS_CONFIG['host']}:{PACKET_LOSS_CONFIG['config_path']}"
            }
        except Exception as e:
            health_status["packet_loss"] = {
                "status": "unhealthy",
                "message": f"连接失败: {str(e)}"
            }
    
    # 判断整体状态
    all_healthy = all(
        status.get("status") in ["healthy", "disabled"]
        for status in health_status.values()
    )
    
    return {
        "status": "healthy" if all_healthy else "unhealthy",
        "details": health_status
    }


# ==================== 一键部署功能 ====================

@router.post("/config-push/deploy/{service_type}")
async def deploy_config_service(service_type: str):
    """
    一键部署配置服务（IP黑名单/域名黑名单/丢包策略）
    
    service_type: ip-blacklist, domain-blacklist, packet-loss
    
    自动执行：
    1. 创建目录结构（配置目录 + 脚本目录）
    2. 上传监控脚本
    3. 检查并安装依赖
    4. 配置sudo权限
    5. 创建systemd服务
    6. 启动监控服务
    7. 验证部署
    """
    import time
    import os
    from datetime import datetime
    
    # 选择对应的配置
    config_map = {
        "ip-blacklist": IP_BLACKLIST_CONFIG,
        "domain-blacklist": DOMAIN_BLACKLIST_CONFIG,
        "packet-loss": PACKET_LOSS_CONFIG
    }
    
    if service_type not in config_map:
        raise HTTPException(status_code=400, detail=f"不支持的服务类型: {service_type}")
    
    config = config_map[service_type]
    
    if not config.get('enabled', False):
        raise HTTPException(status_code=503, detail=f"{service_type}服务未在config.py中启用")
    
    progress_log = []
    
    def log_progress(step: str, status: str, message: str):
        progress_log.append({
            'step': step,
            'status': status,
            'message': message,
            'timestamp': datetime.now().isoformat()
        })
        logger.info(f"[部署-{service_type}] {step}: {message}")
    
    try:
        # 建立SSH连接
        log_progress("连接SSH", "running", f"正在连接到 {config['host']}:{config['port']}...")
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(
            config['host'],
            port=config['port'],
            username=config['username'],
            password=config['password'],
            timeout=10
        )
        log_progress("连接SSH", "success", "SSH连接成功")
        
        # 步骤1: 创建目录结构
        log_progress("创建目录", "running", "正在创建目录结构...")
        commands = [
            "mkdir -p /opt/suppression_config",
            "mkdir -p /opt/suppression_scripts",
            f"chown -R {config['username']}:{config['username']} /opt/suppression_config",
            f"chown -R {config['username']}:{config['username']} /opt/suppression_scripts"
        ]
        
        for cmd in commands:
            stdin, stdout, stderr = ssh.exec_command(f"sudo {cmd}")
            exit_status = stdout.channel.recv_exit_status()
            if exit_status != 0:
                error_msg = stderr.read().decode('utf-8')
                log_progress("创建目录", "error", f"命令失败: {cmd}, 错误: {error_msg}")
                raise Exception(f"创建目录失败: {error_msg}")
        
        log_progress("创建目录", "success", "目录结构创建成功")
        
        # 步骤2: 上传监控脚本
        log_progress("上传脚本", "running", "正在上传监控脚本...")
        sftp = ssh.open_sftp()
        
        # 确定要上传的脚本文件
        script_map = {
            "ip-blacklist": "gateway_black_white_file.py",
            "domain-blacklist": "dns_black_white_file.py",
            "packet-loss": "gateway_packet_loss_file.py"
        }
        
        script_file = script_map[service_type]
        script_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'suppression_scripts')
        local_script = os.path.join(script_dir, script_file)
        remote_script = f"/opt/suppression_scripts/{script_file}"
        
        if not os.path.exists(local_script):
            raise Exception(f"本地脚本不存在: {local_script}")
        
        # 读取并上传脚本（使用二进制模式避免编码问题）
        with open(local_script, 'r', encoding='utf-8') as f:
            content = f.read()
        
        content_bytes = content.encode('utf-8')
        
        with sftp.open(remote_script, 'wb') as remote_f:
            remote_f.write(content_bytes)
        
        sftp.chmod(remote_script, 0o755)
        log_progress("上传脚本", "success", f"监控脚本上传成功: {script_file}")
        
        # 创建初始配置文件
        log_progress("创建配置", "running", "正在创建初始配置文件...")
        if service_type == "ip-blacklist":
            config_file = "/opt/suppression_config/ip_blacklist.txt"
            content = "# IP Blacklist - Auto-generated by platform\n# Add one IP per line\n"
        elif service_type == "domain-blacklist":
            config_file = "/opt/suppression_config/domain_blacklist.txt"
            content = "# Domain Blacklist - Auto-generated by platform\n# Add one domain per line\n"
        else:  # packet-loss
            config_file = "/opt/suppression_config/packet_loss.json"
            content = json.dumps({}, indent=2)
        
        with sftp.open(config_file, 'w') as f:
            f.write(content)
        
        sftp.close()
        log_progress("创建配置", "success", f"配置文件创建成功: {config_file}")
        
        # 步骤3: 检查并安装依赖
        log_progress("安装依赖", "running", "正在检查并安装依赖...")
        
        if service_type == "ip-blacklist":
            # IP黑名单需要: ipset, iptables, python3-watchdog
            deps_check = [
                ("ipset --version", "ipset", "sudo apt-get update && sudo apt-get install -y ipset"),
                ("iptables --version", "iptables", "sudo apt-get install -y iptables"),
            ]
        elif service_type == "domain-blacklist":
            # 域名黑名单需要: dnsmasq, python3-watchdog
            # 先禁用systemd-resolved避免端口冲突
            log_progress("解决冲突", "running", "正在禁用systemd-resolved...")
            resolve_cmds = [
                "sudo systemctl stop systemd-resolved",
                "sudo systemctl disable systemd-resolved",
                "sudo rm -f /etc/resolv.conf",
                "echo 'nameserver 8.8.8.8' | sudo tee /etc/resolv.conf"
            ]
            for cmd in resolve_cmds:
                ssh.exec_command(cmd)
            log_progress("解决冲突", "success", "systemd-resolved已禁用")
            
            deps_check = [
                ("dnsmasq --version", "dnsmasq", "sudo apt-get update && sudo apt-get install -y dnsmasq"),
            ]
        else:  # packet-loss
            # 丢包策略需要: iptables, python3-watchdog
            deps_check = [
                ("iptables --version", "iptables", "sudo apt-get install -y iptables"),
            ]
        
        # 检查并安装系统依赖
        for check_cmd, dep_name, install_cmd in deps_check:
            stdin, stdout, stderr = ssh.exec_command(check_cmd)
            if stdout.channel.recv_exit_status() != 0:
                log_progress("安装依赖", "running", f"{dep_name}未安装，正在安装...")
                ssh.exec_command(install_cmd)
                time.sleep(2)
                log_progress("安装依赖", "success", f"{dep_name}安装成功")
            else:
                log_progress("安装依赖", "success", f"{dep_name}已安装，跳过")
        
        # 安装Python watchdog
        log_progress("安装依赖", "running", "正在安装Python watchdog...")
        stdin, stdout, stderr = ssh.exec_command("pip3 list | grep watchdog")
        if stdout.channel.recv_exit_status() != 0:
            ssh.exec_command("pip3 install watchdog --user")
            log_progress("安装依赖", "success", "watchdog安装成功")
        else:
            log_progress("安装依赖", "success", "watchdog已安装，跳过")
        
        # 步骤4: 配置sudo权限
        log_progress("配置权限", "running", "正在配置sudo免密码...")
        
        if service_type == "ip-blacklist":
            sudoers_line = f"{config['username']} ALL=(ALL) NOPASSWD: /usr/bin/python3, /usr/sbin/ipset, /usr/sbin/iptables"
            sudoers_file = "/etc/sudoers.d/ip-blacklist-monitor"
        elif service_type == "domain-blacklist":
            sudoers_line = f"{config['username']} ALL=(ALL) NOPASSWD: /usr/bin/python3, /usr/bin/systemctl"
            sudoers_file = "/etc/sudoers.d/dns-blacklist-monitor"
        else:  # packet-loss
            sudoers_line = f"{config['username']} ALL=(ALL) NOPASSWD: /usr/bin/python3, /usr/sbin/iptables"
            sudoers_file = "/etc/sudoers.d/packet-loss-monitor"
        
        ssh.exec_command(f"echo '{sudoers_line}' | sudo tee {sudoers_file}")
        ssh.exec_command(f"sudo chmod 0440 {sudoers_file}")
        log_progress("配置权限", "success", "sudo权限配置成功")
        
        # 步骤5: 创建systemd服务
        log_progress("创建服务", "running", "正在创建systemd服务...")
        
        service_map = {
            "ip-blacklist": ("ip-blacklist-monitor", "IP Blacklist Monitor Service"),
            "domain-blacklist": ("dns-blacklist-monitor", "DNS Blacklist Monitor Service"),
            "packet-loss": ("packet-loss-monitor", "Packet Loss Monitor Service")
        }
        
        service_name, service_desc = service_map[service_type]
        
        service_content = f"""[Unit]
Description={service_desc}
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/opt/suppression_scripts
ExecStart=/usr/bin/python3 /opt/suppression_scripts/{script_file} --config-path /opt/suppression_config
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
"""
        
        stdin, stdout, stderr = ssh.exec_command(f"sudo tee /etc/systemd/system/{service_name}.service")
        stdin.write(service_content)
        stdin.channel.shutdown_write()
        stdout.channel.recv_exit_status()
        
        ssh.exec_command(f"sudo chmod 644 /etc/systemd/system/{service_name}.service")
        log_progress("创建服务", "success", "systemd服务创建成功")
        
        # 步骤6: 启动服务
        log_progress("启动服务", "running", "正在启动监控服务...")
        
        ssh.exec_command("sudo systemctl daemon-reload")
        ssh.exec_command(f"sudo systemctl stop {service_name}")
        time.sleep(1)
        ssh.exec_command(f"sudo systemctl start {service_name}")
        ssh.exec_command(f"sudo systemctl enable {service_name}")
        time.sleep(2)
        
        # 检查服务状态
        stdin, stdout, stderr = ssh.exec_command(f"sudo systemctl is-active {service_name}")
        service_status = stdout.read().decode('utf-8').strip()
        
        if service_status == 'active':
            log_progress("启动服务", "success", f"{service_desc}已启动")
        else:
            log_progress("启动服务", "warning", f"服务状态: {service_status}")
        
        # 步骤7: 验证部署
        log_progress("验证部署", "running", "正在验证部署...")
        time.sleep(1)
        
        stdin, stdout, stderr = ssh.exec_command("ls -la /opt/suppression_scripts/")
        script_output = stdout.read().decode('utf-8')
        
        if script_file in script_output:
            log_progress("验证部署", "success", "脚本文件验证通过")
        else:
            log_progress("验证部署", "warning", "脚本文件可能不完整")
        
        ssh.close()
        
        log_progress("部署完成", "success", f"✅ {service_type}服务部署成功！服务器: {config['host']}")
        
        return {
            'status': 'success',
            'message': f'{service_type}服务部署成功',
            'host': config['host'],
            'config_path': config['config_path'],
            'service_name': service_name,
            'service_status': service_status,
            'logs': progress_log
        }
        
    except paramiko.AuthenticationException:
        log_progress("连接SSH", "error", "SSH认证失败，请检查用户名和密码")
        return {
            'status': 'error',
            'message': 'SSH认证失败',
            'logs': progress_log
        }
    except paramiko.SSHException as e:
        log_progress("SSH错误", "error", f"SSH连接错误: {str(e)}")
        return {
            'status': 'error',
            'message': f'SSH错误: {str(e)}',
            'logs': progress_log
        }
    except Exception as e:
        log_progress("未知错误", "error", f"部署失败: {str(e)}")
        logger.exception(f"部署{service_type}服务失败")
        return {
            'status': 'error',
            'message': str(e),
            'logs': progress_log
        }


@router.get("/config-push/status/{service_type}")
async def get_config_service_status(service_type: str):
    """获取配置服务的部署和运行状态"""
    config_map = {
        "ip-blacklist": (IP_BLACKLIST_CONFIG, ip_blacklist_manager),
        "domain-blacklist": (DOMAIN_BLACKLIST_CONFIG, domain_blacklist_manager),
        "packet-loss": (PACKET_LOSS_CONFIG, packet_loss_manager)
    }
    
    if service_type not in config_map:
        raise HTTPException(status_code=400, detail=f"不支持的服务类型: {service_type}")
    
    config, manager = config_map[service_type]
    
    if not config.get('enabled', False):
        return {
            'status': 'error',
            'message': '服务未启用'
        }
    
    if not manager:
        return {
            'status': 'error',
            'message': '管理器未初始化'
        }
    
    try:
        ssh = paramiko.SSHClient()
        ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        ssh.connect(
            config['host'],
            port=config['port'],
            username=config['username'],
            password=config['password'],
            timeout=5
        )
        
        # 检查目录是否存在
        stdin, stdout, stderr = ssh.exec_command(f"test -d {config['config_path']} && echo 'exists' || echo 'not_exists'")
        dir_exists = stdout.read().decode('utf-8').strip() == 'exists'
        
        # 检查配置文件
        file_map = {
            "ip-blacklist": "ip_blacklist.txt",
            "domain-blacklist": "domain_blacklist.txt",
            "packet-loss": "packet_loss.json"
        }
        config_file = file_map.get(service_type, "")
        
        stdin, stdout, stderr = ssh.exec_command(f"test -f {config['config_path']}/{config_file} && echo 'exists' || echo 'not_exists'")
        file_exists = stdout.read().decode('utf-8').strip() == 'exists'
        
        ssh.close()
        
        return {
            'status': 'success',
            'data': {
                'is_deployed': dir_exists and file_exists,
                'is_configured': config.get('enabled', False),
                'host': config['host'],
                'config_path': config['config_path'],
                'config_file': config_file if file_exists else None
            }
        }
    except Exception as e:
        return {
            'status': 'error',
            'message': str(e)
        }
